# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Development Deployment

on:
  push:
    branches:
      - onprem

jobs:
  build:
    runs-on: docker
    steps:
      - uses: http://gitea.com/actions/checkout@v3
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: docker
    steps:
      - uses: http://gitea.com/actions/checkout@v3
      - uses: http://gitea.com/actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
        name: Build 
      - run: npm pack
        name: Pack NPM File